# 切换潜行多少次会触发检测
times: 20
# 催生的几率 10 -> 10%
# 催生失败之后会从头开始记录潜行次数
chance: 10
# 检测范围
# 玩家位置为中心的范围内的树才能被催生
x: -2..2
y: -1..1
z: -2..2
# 允许的移动范围大小
# 若玩家在催生过程中xyz任意一轴上移动的距离超过此值, 则从头开始计数
distance: 1
# 生成树后的消息
success: "&a树长出来啦"
# 生成失败的消息
fail: "&c树长不出来"